services:
  adb-neo4j:
    container_name: adb-neo4j
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
      
      # --- THIS IS THE FIX ---
      # Format this as a string containing a JSON array
      NEO4J_PLUGINS: '["graph-data-science", "apoc"]'
      
      NEO4J_apoc_import_file_enabled: true
      NEO4J_dbms_security_procedures_unrestricted: "gds.*,apoc.*"
    volumes:
      - ./import:/var/lib/neo4j/import
      - ./data:/data
    restart: always